server:
  port: 80
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
      defaultZone: http://127.0.0.1:8760/eureka/
spring:
  application:
    name: consumer
