server:
  port: 10086
spring:
  application:
    name: gateway
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8760/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1